# Generated by Django 5.2.4 on 2025-08-04 10:46

import ai_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="Texte utilisé pour générer l'image", verbose_name='Prompt')),
                ('image', models.ImageField(upload_to=ai_generator.models.upload_to_generated_images, verbose_name='Image générée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Temps de génération (secondes)')),
            ],
            options={
                'verbose_name': 'Image générée',
                'verbose_name_plural': 'Images générées',
                'ordering': ['-created_at'],
            },
        ),
    ]
